### ISSUE TITLE
Switch away from using git branch command, use symbolic-ref instead

### ISSUE THREAD

**Issue by drew-gross** [vshatskyi/black-screen#881]
See why here: https://git-blame.blogspot.com/2013/06/checking-current-branch-programatically.html

**Comment by mkenne11** [comment]
I'd like to make sure I understand it correctly.

The utils\Git.ts ["branches"](https://github.com/vshatskyi/black-screen/blob/master/src/utils/Git.ts#L124) function uses the following command to retrieve local branches for the repo:
`git for-each-ref refs/heads --format='%(HEAD)%(refname:short)`

This doesn't use the "git branch" function to determine the name of the current git branch name (as referenced in [git-blame post](https://git-blame.blogspot.com.au/2013/06/checking-current-branch-programatically.html)). However it does rely on the command adding a "*" to the name of the current branch.

Are you suggesting the `git symbolic-ref --short -q HEAD` command be used to determine the name of the active branch, and the utils\Git.ts "branches" function use this name to assign "true" to the isCurrent property of the active branch in the "branches" array returned.

**Comment by drew-gross** [comment]
Yep thats what I meant.

**Comment by mkenne11** [comment]
@drew-gross I created a PR #969 which I believe implements the "git symbolic-ref" to determine the active git branch name. Hope this is correct.
