### ISSUE TITLE
ls doesn't show list mode

### ISSUE THREAD

**Issue by luco** [vshatskyi/black-screen#913]
I have an alias on my `.bash_profile` which works properly on iTerm and Terminal:

`alias ls="ls -la"`

But on Black Screen this simply does not work. Shows a list like I just inserted `ls`.

Any tips?

Thanks

**Comment by drew-gross** [comment]
That is because of a plugin that is overriding the behaviour of ls. Currently there is no way to disable it, but I can work on one.

In the meantime, if you click on the green magic wand, it will disable the plugin for that command.
