### ISSUE TITLE
Autocomplete file/folder names should insert quotes if necessary

### ISSUE THREAD

**Issue by namlook** [vshatskyi/black-screen#927]
![black-screen-issue](https://cloud.githubusercontent.com/assets/86238/21075743/dd0c8516-bf19-11e6-8ad4-c9dd366a24f0.gif)
There are no errors in the Developper's Console...

**Comment by drew-gross** [comment]
This ie expected. You need to use quotes around tokens with brackets. This also applies to bash and other terminals.

**Comment by namlook** [comment]
Hi understand that but, at least, the autocompletion should do that instead of suggesting `\(`. This force me to copy and paste the name of the folder/file and pasting it between quotes...

**Comment by drew-gross** [comment]
Oh yeah good point
