### ISSUE TITLE
Unable to enter new commands after using and entering many other commands

### ISSUE THREAD

**Issue by phillicm** [vshatskyi/black-screen#945]
Apparently not to sure if this is a known issue but the application will hang and unable to enter any new commands. I will have to open a new tab to continue using the application or restarting it.

**Comment by drew-gross** [comment]
Yeah, I've experienced this too. Haven't had the time to debug it yet, it's difficult to reproduce. If you or anyone else finds a way to consistently reproduce this issue, please post the steps here.

**Comment by zyvitski** [comment]
I have this issue quite a lot. Mainly when building and running C++ programs using make. 
The problem arises when repeatedly running "make" to build my project and then running the program which will output several hundred lines to the terminal. 

If I had to guess, the brute force way of reproducing the issue is to write a simple program that outputs a large number of lines to the terminal, and then run that program many times. 

When I encounter the issue I notice that It is a combination of running several commands and each command producing a large amount of output. Just doing one or the other seems to take much longer to reproduce the issue.

I am running on OSX 10.12.2 on a Early 2013 MacBook Pro with Black-Screen v0.2.93 for reference

**Comment by zyvitski** [comment]
I Just took a moment and replicated the error: I dont know how much help the info i can give you will be but here it is anyway. I ran my program that I am working on 24 times. Each time it output 362 lines of text. I recorded the session using the built-in dev tools. I took a quick screen grab of the Dev-Tools Results (I dont know how to save a log of the output) which I can provide upon request. (Github wont let me upload)

**Comment by zyvitski** [comment]
<img width="1294" alt="screen shot 2017-01-19 at 9 17 42 pm" src="https://cloud.githubusercontent.com/assets/5298486/22133272/4c6d3f12-de8d-11e6-9855-44f9f1e53a3b.png">

**Comment by phillicm** [comment]
It happens a lot when I cd and ls which are every simple commands but I am not to sure what really triggers it. Very hard to debug.

**Comment by zyvitski** [comment]
If I had to take a guess, It would have something to do with the input and output buffers getting extremely large. I am not familiar with how the program works, but it may be worth looking into caching the output into a file when it reaches a certain size. This would free up q lot of the memory being used as well as provide a way to enable output logging if there isn't one already. 

For comparison here is the output after running the my program only once:

<img width="1295" alt="screen shot 2017-01-19 at 9 58 06 pm" src="https://cloud.githubusercontent.com/assets/5298486/22134074/7129d126-de92-11e6-9b1e-d74e0898b194.png">

Note how running just once only uses 23.9MB of heap and 916 Nodes as compared to 78.8MB of heap and 111836 Nodes after running 24 times. Those numbers seem to scale in a non linear fashion which to me would indicate a possible source of the issue possibly.

**Comment by drew-gross** [comment]
Does the issue always show up after exactly 24 commands? If so, it would be very useful to see your steps in reproducing.

**Comment by zyvitski** [comment]
Just ran two more trials, the first I ran without recording the info on the dev-tools and It took 20 runs of my program. I ran a second time while recording on the Dev-tools and It indeed did take exactly 24 runs of my program. 
<img width="1296" alt="screen shot 2017-01-20 at 1 50 27 pm" src="https://cloud.githubusercontent.com/assets/5298486/22161231/794b4152-df17-11e6-91f2-802d1a2d5857.png">

**Comment by zyvitski** [comment]
<img width="1290" alt="screen shot 2017-01-20 at 1 53 30 pm" src="https://cloud.githubusercontent.com/assets/5298486/22161329/e3597cf8-df17-11e6-91e4-120b5d8d0ddb.png">
<img width="1290" alt="screen shot 2017-01-20 at 1 53 40 pm" src="https://cloud.githubusercontent.com/assets/5298486/22161330/e35f1bf4-df17-11e6-9f88-bcf04a739bab.png">

**Comment by zyvitski** [comment]
<img width="1294" alt="screen shot 2017-01-20 at 1 54 59 pm" src="https://cloud.githubusercontent.com/assets/5298486/22161378/1090d73e-df18-11e6-993c-64b2119ed496.png">

**Comment by drew-gross** [comment]
Thats interesting. The resident memory growing isn't particularly surprising, since we need to store all that output from your commands, but the bug always triggering after 24 executions is very interesting. If you run a different program (and/or change the program you are running to have shorter or longer output) does that affect the reproducibility?

**Comment by zyvitski** [comment]
Just tested, Ran 'ls' 26 times in a row before it failed. With arrpox 4 lines of output per run. So my guess would it doesn't directly correlate to the number of lines being printed as this is 100x less lines than my previous tests

**Comment by drew-gross** [comment]
I just pushed a new version that fixes several potential causes of the issue. Let me know if it is fixed for you.

**Comment by zyvitski** [comment]
how can I get a copy with the changes? which branch to download or other install instrcutions please?

**Comment by drew-gross** [comment]
On the releases page: https://github.com/vshatskyi/black-screen/releases

**Comment by zyvitski** [comment]
Does not seem to be fixed

**Comment by drew-gross** [comment]
Alright, my most recent PR should finally fix this. It removed some sketchy looking code that could assign the  "current" prompt at a bad time. Let me know if you still encounter this issue.
