### ISSUE TITLE
Not consistent version number in release build url

### ISSUE THREAD

**Issue by Igloczek** [vshatskyi/black-screen#956]
I try to update package version on brew-cask, but faced a weird issue.

`https://github.com/vshatskyi/black-screen/releases/download/v0.2.118/black-screen-0.2.115.dmg`

v0.2.115 is uploaded to v0.2.118 folder and neither v0.2.115 doesn't exist in v0.2.115, same as v0.2.118 doesn't exist in v0.2.118, so basically I can't do anything, b/c pattern for this url is `https://github.com/vshatskyi/black-screen/releases/download/v#{version}/black-screen-#{version}-mac.zip`

**Comment by diederikh** [comment]
I have the same issue.

**Comment by drew-gross** [comment]
0.2.135 should be correct now. The deploy process isn't fixed yet, but you should at least be unblocked for updating brew.
