### ISSUE TITLE
Aliases with quotes, single or double, aren't working

### ISSUE THREAD

**Issue by ainzzorl** [vshatskyi/black-screen#957]
These commands fail:
alias l="ls -l"
alias l='ls -l'
alias l="ls"
alias l='ls'

This succeeds:
alias l=ls

I believe it treats l="ls -l" as 2 arguments: l= and "ls -l", but they should be one.

**Comment by drew-gross** [comment]
Are you talking about in your `.bashrc`?

**Comment by ainzzorl** [comment]
No: see the screenshot.

![screen shot 2017-01-27 at 9 36 03 am](https://cloud.githubusercontent.com/assets/25125937/22380926/40824b06-e474-11e6-9d9d-550a7a26e541.png)

**Comment by drew-gross** [comment]
Cool, thanks for the update.

**Comment by ainzzorl** [comment]
I'd like to try to fix this.

I think the root cause is a bug in the Scanner: every quoted string literal is a separate token, but it shouldn't be. Example: echo a"b"'c'. Expected output: abc, actual: a b c. The simplest way to fix it is to do this: if there are 2 string literals next to each other with no space characters between them, then combine them into one. Does this make sense?

**Comment by drew-gross** [comment]
Yeah, that does. The scanner code always did look a little suspicious to me. We would definitely appreciate the help! (I would also appreciate a test case in `scanner_spec.ts` if you do fix this)
