### ISSUE TITLE
"filesSuggestions" method throwing errors in Ubuntu 16.04

### ISSUE THREAD

**Issue by mkenne11** [vshatskyi/black-screen#967]
I am aware that Linux is not officially supported by black-screen, but thought I'd flag an issue encountered in Ubuntu 16.04.

For a while Ubuntu appears to have set the default shell (using the symbolic link "/bin/sh") to "dash". Dash has trouble handling the command used to escape filenames ('printf %q ...') and throws an error. See command in the **filesSuggestions** method at [Common.ts Line 231](https://github.com/vshatskyi/black-screen/blob/master/src/plugins/autocompletion_utils/Common.ts#L231).

This resulted in file/directory path suggestions not showing for a number of auto-complete providers including Cd and Ls.

Setting the default shell to "bash" stopped this error occuring and file/directory path suggestions worked correctly for auto-complete providers after this. This post shows how to set bash as your default shell:
https://baulshi.wordpress.com/2011/08/03/switch-binsh-of-ubuntu-from-dash-to-bash/

Any suggestions on how to escape file paths in a way that shell commands in dash (and possibly other shells without "printf %q" support) will accept? 

The following stackoverflow answer indicates that "printf %q" prints in a format that escapes non-printable characters with the proposed POSIX $'' syntax (including whitespace). I was unable to find any npm packages or js code snippets that replicate this unfortunately.
http://stackoverflow.com/questions/40573839/how-to-use-printf-q-in-bash/40574048#40574048

**Comment by drew-gross** [comment]
This should be fixed by #696. If not, please comment here.

**Comment by mkenne11** [comment]
Thanks @drew-gross PR #954 did indeed fix this!
