### ISSUE TITLE
Add !! from GNOME Terminal

### ISSUE THREAD

**Issue by wilkoklak** [vshatskyi/black-screen#974]
Could you add ``!!`` from GNOME Terminal?
``!!`` repeats previous command, so for example, if I forgot to add sudo before the command, I don't have to retype it, I just need to write ``sudo !!``

**Comment by minecrawler** [comment]
It's Bash, not "GNOME Terminal", but I second this request

**Comment by vshatskyi** [comment]
Closing in favour of https://github.com/vshatskyi/black-screen/issues/1009
