### ISSUE TITLE
Using zshrc but "nvm" command not found

### ISSUE THREAD

**Issue by tithamane** [vshatskyi/black-screen#975]
Other stuff seem to work but I tried install "nvm" which works with iterm2 but not with black-screen.

The NVM_DIR is defined in my zshrc and black-screen is aware of the fact that I am using zsh.

What could be wrong?
<img width="489" alt="screen shot 2017-02-27 at 11 21 29 am" src="https://cloud.githubusercontent.com/assets/5633403/23355582/11869ed2-fcdf-11e6-9de9-5560d1fc01cf.png">

**Comment by drew-gross** [comment]
I don't know for sure, but I would guess that `nvm` likely works in a similar way to `rvm` and `virtualenv` which is by using shell features that clash with the way `black-screen` works. I don't currently know of a way to fix this.

**Comment by tithamane** [comment]
Thanks for the feedback. [n](https://github.com/tj/n) is a good alternative as it works in black-screen so I use that.

**Comment by brandonweiss** [comment]
@drew-gross Could you expound on this? What features does `nvm` use that clash with how Upterm works?

**Comment by glyif** [comment]
@le0pard wondering if we could continue this convo on why nvm doesn't work on upterm

**Comment by le0pard** [comment]
@glyif don't ask me in each feature - if you can find and fix problem - just do it 😺
