### ISSUE TITLE
Rotating active pane should wrap around

### ISSUE THREAD

**Issue by akivajgordon** [vshatskyi/black-screen#977]
## Context
Suppose I have, say, 3 panes open, and I am advancing to the next pane (like with <kbd>cmd-J</kbd>). For this context, let's say, for example, I'm currently on the last pane.

## Current behavior
Nothing happens when I press <kbd>cmd-J</kbd>.

## Desired behavior
When I press <kbd>cmd-J</kbd>, I should now be on the 1st pane. And similarly, the reverse should be true if try to go to the previous pane when currently on the 1st pane – I should end up on the last one. Basically, it should wrap around.

This would fall in line with how tabs in Black Screen seem to be implemented.

**Comment by mkenne11** [comment]
@drew-gross can this be closed now?

**Comment by drew-gross** [comment]
Yep. Thanks!
