### ISSUE TITLE
"Toggle Full Screen" and "Find" keybindings are identical

### ISSUE THREAD

**Issue by akivajgordon** [vshatskyi/black-screen#978]
The keybindings/shortcuts for both "Toggle Full Screen" and "Find" are identically <kbd>⌘F</kbd>. When I try to "Find" something, it only toggles full screen mode.

In either case, the "Toggle Full Screen" command should be <kbd>⌃⌘F</kbd> as it is in all native macOS apps.

**Comment by akivajgordon** [comment]
Ok, so I actually see that the duplicate keybinding was changed in [this commit](https://github.com/vshatskyi/black-screen/commit/b658af80c86026cddc412ba48ab41c126394d95d), but I'm not a fan of the choice of <kbd>⇧⌘F</kbd> instead of the more ubiquitous <kbd>⌃⌘F</kbd>.

**Comment by drew-gross** [comment]
I totally agree, it's best to always match the operating system conventions. Want to submit a PR to fix this?
