### ISSUE TITLE
Instructions for debugging black-screen in vscode

### ISSUE THREAD

**Issue by mkenne11** [vshatskyi/black-screen#998]
I have written some instructions for debugging black-screen in vscode. I have tested these myself in Ubuntu, but not Mac OS or Windows.
https://github.com/mkenne11/black-screen/blob/vscode_debug_instructions/docs/vscodedebugging.md

The debug configuration took a while for me to get right.

@drew-gross if you think this is worth sharing let me know and I'd be happy to create a pull request of publish in the black-screen wiki.

**Comment by drew-gross** [comment]
That is very cool! I would definitely merge a PR that added this.

**Comment by mkenne11** [comment]
No worries I'll raise a PR soon. Btw I'm curious - What tools do u use to edit and debug the project?

**Comment by drew-gross** [comment]
I use sublime text to edit and the chrome developer tools to debug

**Comment by mkenne11** [comment]
Thanks, I'll have to try chrome developer tools to debug, TBH I have only used it to look at timing and memory usage profiles. I do like that vscode gives you the flexibility of debugging at the Typescript level, or the (transpiled) Javascipt files.
